modLoader = "javafml" #mandatory
loaderVersion = "[3,)" #mandatory
license = "${license}" # Review your options at https://choosealicense.com/.
issueTrackerURL="${repo}/issues" #optional
[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${version}" #mandatory
displayName = "${mod_name}" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://docs.neoforged.net/docs/misc/updatechecker/)
displayURL="https://sweetberry.dev/" #optional (displayed in the mod UI)
logoFile="assets/${mod_id}/icon.png" #optional
authors = "Sweet Berry Collective" #optional
description = '''${mod_description}''' #mandatory (Supports multiline text)
[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.client.mixins.json"
side = "CLIENT"
[[mixins]]
config = "${mod_id}.neoforge.mixins.json"
[[mixins]]
config = "${mod_id}.neoforge.client.mixins.json"
side = "CLIENT"
#[[accessTransformers]]
#file="accesstransformer.cfg"
[[dependencies.${mod_id}]] #optional
modId = "neoforge" #mandatory
type="required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[2,)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'
[[dependencies.${mod_id}]]
modId = "minecraft"
type="required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[${min_minecraft},${max_minecraft}]"
ordering = "NONE"
side = "BOTH"
